[character]
success_symbol = "[ï”](green)"
error_symbol = "[ï”](red)"

[sudo]
disabled = false
symbol = "ğŸ§™ "

[python]
python_binary = ["./venv/bin/python3", "python3"]
style = "green bold"

[git_branch]
symbol = "ï˜ "
style = "bold fg:#B585E6"

[git_status]
style = "bold fg:#B585E6"
